include(FetchContent)
# Immutable upstream revisions; no tracking branches in reproducible builds.
set(SDL_SHARED OFF CACHE BOOL "" FORCE)
set(SDL_STATIC ON CACHE BOOL "" FORCE)
set(SDL_TEST_LIBRARY OFF CACHE BOOL "" FORCE)
set(SDL_TESTS OFF CACHE BOOL "" FORCE)
set(SDL_OPENGL OFF CACHE BOOL "" FORCE)
set(SDL_OPENGLES OFF CACHE BOOL "" FORCE)
set(SDL_RENDER OFF CACHE BOOL "" FORCE)
set(SDL_GPU OFF CACHE BOOL "" FORCE)
set(SDL_AUDIO OFF CACHE BOOL "" FORCE)
set(SDL_CAMERA OFF CACHE BOOL "" FORCE)
set(FLECS_STATIC ON CACHE BOOL "" FORCE)
set(FLECS_SHARED OFF CACHE BOOL "" FORCE)
set(FLECS_TESTS OFF CACHE BOOL "" FORCE)
FetchContent_Declare(sdl GIT_REPOSITORY https://github.com/libsdl-org/SDL.git GIT_TAG 7f3ae3d57459e59943a4ecfefc8f6277ec6bf540)
FetchContent_Declare(flecs GIT_REPOSITORY https://github.com/SanderMertens/flecs.git GIT_TAG a53b4715c0b91e366bbfce53d9abd2b61534f7a3)
FetchContent_Declare(imgui GIT_REPOSITORY https://github.com/ocornut/imgui.git GIT_TAG af84778eeaab75bee0b54420f3157cf3ee00618f)
FetchContent_Declare(implot GIT_REPOSITORY https://github.com/epezent/implot.git GIT_TAG 4707b245fbcd69075b1a8a74fa8d2435561b3134)
FetchContent_Declare(imguizmo GIT_REPOSITORY https://github.com/CedricGuillemet/ImGuizmo.git
  GIT_TAG 18cef5e031d8c6973d80284c67f60549fafd78c1 SOURCE_SUBDIR souls-standalone)
FetchContent_MakeAvailable(sdl flecs imgui implot)
if(WIN32)
  if(NOT CMAKE_SIZEOF_VOID_P EQUAL 8 OR CMAKE_SYSTEM_PROCESSOR MATCHES "ARM|arm")
    message(FATAL_ERROR "This Agility deployment is x64; configure an x64 Windows toolchain")
  endif()
  FetchContent_Declare(agility URL https://www.nuget.org/api/v2/package/Microsoft.Direct3D.D3D12/1.616.1 URL_HASH SHA256=3D8F4AF714947C8B64B5656F48DEB08661D6A5F743D97C63766065BD633AD52E DOWNLOAD_EXTRACT_TIMESTAMP TRUE)
  FetchContent_MakeAvailable(agility)
  set(imgui_backend "${imgui_SOURCE_DIR}/backends/imgui_impl_dx12.cpp")
endif()
if(NOT WIN32 OR SOULS_VULKAN_COMPILE_CHECK)
  FetchContent_Declare(vulkan_headers GIT_REPOSITORY https://github.com/KhronosGroup/Vulkan-Headers.git GIT_TAG 19725e4d48082fe78e26622b15d3080ccd54112b)
  FetchContent_Declare(volk GIT_REPOSITORY https://github.com/zeux/volk.git GIT_TAG f30088b3f4160810b53e19258dd2f7395e5f0ba3)
  FetchContent_MakeAvailable(vulkan_headers)
  set(VOLK_PULL_IN_VULKAN OFF CACHE BOOL "" FORCE)
  FetchContent_MakeAvailable(volk)
  target_link_libraries(volk PUBLIC Vulkan::Headers)
  if(NOT WIN32)
    set(imgui_backend "${imgui_SOURCE_DIR}/backends/imgui_impl_vulkan.cpp")
  endif()
endif()
add_library(SoulsImGui STATIC
  "${imgui_SOURCE_DIR}/imgui.cpp" "${imgui_SOURCE_DIR}/imgui_draw.cpp"
  "${imgui_SOURCE_DIR}/imgui_tables.cpp" "${imgui_SOURCE_DIR}/imgui_widgets.cpp"
  "${imgui_SOURCE_DIR}/backends/imgui_impl_sdl3.cpp" ${imgui_backend})
target_include_directories(SoulsImGui SYSTEM PUBLIC "${imgui_SOURCE_DIR}" "${imgui_SOURCE_DIR}/backends")
target_link_libraries(SoulsImGui PUBLIC SDL3::SDL3)
if(WIN32)
  target_include_directories(SoulsImGui SYSTEM PUBLIC "${agility_SOURCE_DIR}/build/native/include")
  target_link_libraries(SoulsImGui PRIVATE d3d12 dxgi d3dcompiler)
else()
  target_compile_definitions(SoulsImGui PUBLIC IMGUI_IMPL_VULKAN_USE_VOLK VK_NO_PROTOTYPES)
  target_link_libraries(SoulsImGui PUBLIC volk)
endif()
add_library(SoulsImPlot STATIC "${implot_SOURCE_DIR}/implot.cpp" "${implot_SOURCE_DIR}/implot_items.cpp")
target_include_directories(SoulsImPlot SYSTEM PUBLIC "${implot_SOURCE_DIR}")
target_link_libraries(SoulsImPlot PUBLIC SoulsImGui)
# Only the transform widget is needed; do not build the sequencer and graph samples.
FetchContent_MakeAvailable(imguizmo)
add_library(SoulsImGuizmo STATIC "${imguizmo_SOURCE_DIR}/src/ImGuizmo.cpp")
target_include_directories(SoulsImGuizmo SYSTEM PUBLIC "${imguizmo_SOURCE_DIR}/src")
target_link_libraries(SoulsImGuizmo PUBLIC SoulsImGui)
# Third-party sources keep their own warning/exception policy.
