if(NOT EXT)
 set(EXT bin)
endif()
file(WRITE "${OUTPUT}" "#pragma once\n#include <array>\n#include <cstdint>\nnamespace souls::shaders {\n")
foreach(name IN ITEMS mesh_vs mesh_ps grid_vs grid_ps)
 file(READ "${INPUT}/${name}.${EXT}" data HEX)
 string(LENGTH "${data}" length)
 math(EXPR count "${length}/8")
 file(APPEND "${OUTPUT}" "inline constexpr std::array<std::uint32_t,${count}> ${name}={\n")
 math(EXPR end "${length}-8")
 foreach(offset RANGE 0 ${end} 8)
  string(SUBSTRING "${data}" ${offset} 8 word)
  string(REGEX REPLACE "(..)(..)(..)(..)" "0x\\4\\3\\2\\1u," word "${word}")
  file(APPEND "${OUTPUT}" "${word}")
 endforeach()
 file(APPEND "${OUTPUT}" "};\n")
endforeach()
file(APPEND "${OUTPUT}" "}\n")
