if(WIN32)
 FetchContent_Declare(dxc URL https://www.nuget.org/api/v2/package/Microsoft.Direct3D.DXC/1.8.2505.32 URL_HASH SHA256=c6e82b70c14552f1dd58e4a79c93eeab1567eeb0a9ee63a51564c410429bce3e DOWNLOAD_EXTRACT_TIMESTAMP TRUE)
 FetchContent_MakeAvailable(dxc)
 find_program(SOULS_DXC dxc.exe PATHS "${dxc_SOURCE_DIR}/build/native/bin/x64" NO_DEFAULT_PATH REQUIRED)
 set(shader_options)
else()
 if(NOT CMAKE_SYSTEM_PROCESSOR MATCHES "x86_64|AMD64")
  message(FATAL_ERROR "Set SOULS_DXC to a native DXC executable for this Linux architecture")
 endif()
 if(NOT SOULS_DXC)
  FetchContent_Declare(dxc_linux URL https://github.com/microsoft/DirectXShaderCompiler/releases/download/v1.8.2505.1/linux_dxc_2025_07_14.x86_64.tar.gz URL_HASH SHA256=f2213da1fc99dc8778c8823078e16ba97c7f80f86a1d4520ab1adf4b462bc48c DOWNLOAD_EXTRACT_TIMESTAMP TRUE)
  FetchContent_MakeAvailable(dxc_linux)
  find_program(SOULS_DXC dxc PATHS "${dxc_linux_SOURCE_DIR}/bin" NO_DEFAULT_PATH REQUIRED)
 endif()
 set(shader_options -spirv -fspv-target-env=vulkan1.3 -D SPIRV=1)
endif()
set(shader_dir "${CMAKE_CURRENT_BINARY_DIR}/shaders")
file(MAKE_DIRECTORY "${shader_dir}")
set(shader_binaries)
foreach(pair IN ITEMS "mesh_vs,VSMain,vs_6_0" "mesh_ps,PSMain,ps_6_0" "grid_vs,GridVS,vs_6_0" "grid_ps,GridPS,ps_6_0")
 string(REPLACE "," ";" parts "${pair}")
 list(GET parts 0 name)
 list(GET parts 1 entry)
 list(GET parts 2 profile)
 set(vertex_y_options)
 set(native_y_options)
 if(profile MATCHES "^vs_")
  set(vertex_y_options -fvk-invert-y)
  if(NOT WIN32)
   set(native_y_options ${vertex_y_options})
  endif()
 endif()
 add_custom_command(OUTPUT "${shader_dir}/${name}.bin"
  COMMAND "${SOULS_DXC}" -E ${entry} -T ${profile} -WX -Ges -O3 ${shader_options} ${native_y_options} -Fo "${shader_dir}/${name}.bin" "${CMAKE_CURRENT_SOURCE_DIR}/shaders/Playground.hlsl"
  DEPENDS shaders/Playground.hlsl VERBATIM)
 list(APPEND shader_binaries "${shader_dir}/${name}.bin")
 if(WIN32 AND SOULS_VULKAN_COMPILE_CHECK)
  add_custom_command(OUTPUT "${shader_dir}/${name}.spv"
   COMMAND "${SOULS_DXC}" -E ${entry} -T ${profile} -WX -Ges -O3 -spirv -fspv-target-env=vulkan1.3 -D SPIRV=1 ${vertex_y_options} -Fo "${shader_dir}/${name}.spv" "${CMAKE_CURRENT_SOURCE_DIR}/shaders/Playground.hlsl"
   DEPENDS shaders/Playground.hlsl VERBATIM)
  list(APPEND vulkan_shader_binaries "${shader_dir}/${name}.spv")
 endif()
endforeach()
if(vulkan_shader_binaries)
 add_custom_target(SoulsVulkanShadersCompileCheck ALL DEPENDS ${vulkan_shader_binaries})
 file(MAKE_DIRECTORY "${shader_dir}/vulkan-check")
 add_custom_command(OUTPUT "${shader_dir}/vulkan-check/ShaderData.hpp"
  COMMAND ${CMAKE_COMMAND} "-DINPUT=${shader_dir}" "-DEXT=spv" "-DOUTPUT=${shader_dir}/vulkan-check/ShaderData.hpp" -P "${CMAKE_CURRENT_SOURCE_DIR}/cmake/EmbedShaders.cmake"
  DEPENDS ${vulkan_shader_binaries} cmake/EmbedShaders.cmake VERBATIM)
 add_library(SoulsVulkanRendererCheck STATIC src/renderer/Renderer.cpp "${shader_dir}/vulkan-check/ShaderData.hpp")
 target_include_directories(SoulsVulkanRendererCheck PRIVATE include "${shader_dir}/vulkan-check")
 target_compile_definitions(SoulsVulkanRendererCheck PUBLIC SOULS_RHI_VULKAN=1)
 target_link_libraries(SoulsVulkanRendererCheck PUBLIC SoulsCore SoulsScene SoulsVulkanCompileCheck)
 add_executable(SoulsVulkanRuntimeCheck src/runtime/main.cpp)
 target_link_libraries(SoulsVulkanRuntimeCheck PRIVATE SoulsVulkanRendererCheck SoulsDemo SoulsBrand SDL3::SDL3 volk)
 if(BUILD_TESTING)
  add_test(NAME SoulsVulkanRuntimeCheck.smoke COMMAND SoulsVulkanRuntimeCheck --smoke 120)
  set_tests_properties(SoulsVulkanRuntimeCheck.smoke PROPERTIES LABELS "gpu;interactive" TIMEOUT 90)
 endif()
endif()
add_custom_command(OUTPUT "${shader_dir}/ShaderData.hpp" COMMAND ${CMAKE_COMMAND} "-DINPUT=${shader_dir}" "-DOUTPUT=${shader_dir}/ShaderData.hpp" -P "${CMAKE_CURRENT_SOURCE_DIR}/cmake/EmbedShaders.cmake" DEPENDS ${shader_binaries} cmake/EmbedShaders.cmake VERBATIM)
target_sources(SoulsRenderer PRIVATE "${shader_dir}/ShaderData.hpp")
target_include_directories(SoulsRenderer PRIVATE "${shader_dir}")
